# Waybar
$WaybarBackground = #303030
$WaybarHighlight = #202020
$WaybarText = #FF1000

# Hyprlock


# Hyprland


# FireFox


# VS Code


#$accent = $mauve
#$accentAlpha = $mauveAlpha
#$font = JetBrainsMono Nerd Font