# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

preload = /home/eh-sora/.config/hypr/BG/HyprDeskBG.jpg

wallpaper = eDP-1,/home/eh-sora/.config/hypr/BG/HyprDeskBG.jpg

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off