# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

preload = /home/eh-sora/Bilder/BG/SwayBG.jpeg

wallpaper = eDP-1,/home/eh-sora/Bilder/BG/SwayBG.jpeg